### PR TITLE
Fix debounce immediate

### LINKED ISSUE #2478: there may be some problems with  _.debounce
in this file <https://github.com/jashkenas/underscore/blob/master/underscore.js>

I think there may be some issues in _.debounce function, if we use like this

```
var lazyLayout = _.debounce(function() {
	console.log(123)
	} , 300, true);

window.onresize = lazyLayout;
```

there will be only one '123' in the console after resizing the window several times.

### PR DESCRIPTION
**Pull request by jridgewell**
Fixes an issue with `_.debounce` when `{ immediate: true }`. When
called twice within `wait` ms, we cleared the `timeout`. Because it is
truthy on the second run, it was cleared but `timeout` remained
truthy (on any later run, `timeout` remains truthy). Because `timeout`
was cleared, the `later` function is never run to null out `timeout`.

Anyways, we should always be setting a fresh timeout function when
`{ immediate: true }`, to prevent further calls to the debounced
function until the `wait` ms after the last call.

Fixes #2478, supersedes #2479. Thanks for the bug report @hanzichi.

### CODE REVIEW

**Comment by megawac** [comment]
Fine with this change, but did that not pass before?

**Comment by jridgewell** [comment]
The old tests pass, but nothing tested calling the debounced function again after `wait` is over.

File: underscore.js [hunk 1]
```diff
@@ -862,10 +862,10 @@
     var debounced = restArgs(function(args) {
       var callNow = immediate && !timeout;
```
Comment (captbaritone) [inline underscore.js]: This is now only used inside the `if(immediate) {` block. Could we move it into that block?

Comment (jridgewell) [inline underscore.js]: Updated.

**Comment by bent0b0x** [comment]
Is thee a way to tell in which version of underscore this is fixed?

**Comment by hanzichi** [comment]
@bent0b0x it was not in the released versions,  it was fixed in the edge version, so the bug is not in any one of the released ones
